In [1]:
import pandas as pd

# Parler

In [25]:
df=pd.read_csv("../Naman/final_csv/parler_final.csv")
df

,Unnamed: 0,creator,user_followers,user_following,#comments,#posts,ratio_following_followers,ratio_comments_posts
0,0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,25.0,195.0,0.302368,0.128205
1,1,a078092e6e2df507bfd12db4713f2db7,33.0,13.0,0.0,0.0,0.393939,1.000000
2,2,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,0.0,0.0,0.328333,1.000000
3,3,a078092e6e2df507bfd12db4710da666,307.0,28.0,0.0,0.0,0.091205,1.000000
4,4,a078092e6e2df507bfd12db471072e00,1600.0,134.0,0.0,0.0,0.083750,1.000000
...,...,...,...,...,...,...,...,...
10789017,12342704,119521e88cf9484a87afa91a9c9c8339,0.0,1.0,0.0,0.0,inf,1.000000
10789018,12342706,dfe689b9e9fc4974865d09f1d7d72597,1.0,12.0,0.0,0.0,12.000000,1.000000
10789019,12342707,6eb75d964f824b02923cab1cc2ffbcdb,0.0,9.0,0.0,0.0,inf,1.000000
10789020,12342708,66f57099e57842d2be2d2ec9ce69657f,0.0,2.0,0.0,0.0,inf,1.000000
10789021,12342710,4cee5a4de9224a13bc34af6cb4f88bfd,0.0,1.0,0.0,0.0,inf,1.000000

## posts

In [10]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['#posts'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.9868061562112012

In [26]:
import numpy as np

#define function to calculate Gini coefficient
def gini(x):
    total = 0
    for i, xi in enumerate(x[:-1], 1):
        total += np.sum(np.abs(xi - x[i:]))
    return total / (len(x)**2 * np.mean(x))

gini_index = gini_coefficient(df['#posts'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.9868061562112012

## comments

In [9]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['#comments'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.993616797992123

In [8]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['user_following'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.8287543278277039

In [11]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['user_followers'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.9626804093239837

# Dotwin

# posts

In [13]:
df=pd.read_csv("../Naman/final_csv/dotwin_final.csv")
df

,Unnamed: 0,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,0,--1--,1.0,1.0,37.0,231.0,0.160173,1.00
1,1,-2b-,221.0,5.0,58.0,258.0,0.224806,44.20
2,2,-Lin-Wood,7.0,1.0,6.0,13.0,0.461538,7.00
3,3,-ProudPatriot-,1.0,4.0,1.0,23.0,0.043478,0.25
4,4,-REEEEEEEDACTED-,1.0,2.0,103.0,1029.0,0.100097,0.50
...,...,...,...,...,...,...,...,...
48089,48089,zyklonbravo,0.0,0.0,66.0,73.0,0.904110,1.00
48090,48090,zz556,0.0,0.0,7.0,11.0,0.636364,1.00
48091,48091,zzRrocks,0.0,0.0,13.0,27.0,0.481481,1.00
48092,48092,zzyzxx,0.0,0.0,2.0,2.0,1.000000,1.00
48093,48093,zzyzzx,0.0,0.0,14.0,18.0,0.777778,1.00

In [14]:
df.columns

Index(['Unnamed: 0', 'author', 'comments_received', '#posts', '#comments',
       'karma', 'ratio_#comments_karma', 'ratio_comments_received_#posts'],
      dtype='object')

In [18]:
df=df.drop("Unnamed: 0",axis=1)
df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,--1--,1.0,1.0,37.0,231.0,0.160173,1.00
1,-2b-,221.0,5.0,58.0,258.0,0.224806,44.20
2,-Lin-Wood,7.0,1.0,6.0,13.0,0.461538,7.00
3,-ProudPatriot-,1.0,4.0,1.0,23.0,0.043478,0.25
4,-REEEEEEEDACTED-,1.0,2.0,103.0,1029.0,0.100097,0.50
...,...,...,...,...,...,...,...
48089,zyklonbravo,0.0,0.0,66.0,73.0,0.904110,1.00
48090,zz556,0.0,0.0,7.0,11.0,0.636364,1.00
48091,zzRrocks,0.0,0.0,13.0,27.0,0.481481,1.00
48092,zzyzxx,0.0,0.0,2.0,2.0,1.000000,1.00
48093,zzyzzx,0.0,0.0,14.0,18.0,0.777778,1.00

In [19]:
df.to_csv("../Naman/final_csv/dotwin_final.csv",index=False)

In [20]:
df=pd.read_csv("../Naman/final_csv/dotwin_final.csv")
df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,--1--,1.0,1.0,37.0,231.0,0.160173,1.00
1,-2b-,221.0,5.0,58.0,258.0,0.224806,44.20
2,-Lin-Wood,7.0,1.0,6.0,13.0,0.461538,7.00
3,-ProudPatriot-,1.0,4.0,1.0,23.0,0.043478,0.25
4,-REEEEEEEDACTED-,1.0,2.0,103.0,1029.0,0.100097,0.50
...,...,...,...,...,...,...,...
48089,zyklonbravo,0.0,0.0,66.0,73.0,0.904110,1.00
48090,zz556,0.0,0.0,7.0,11.0,0.636364,1.00
48091,zzRrocks,0.0,0.0,13.0,27.0,0.481481,1.00
48092,zzyzxx,0.0,0.0,2.0,2.0,1.000000,1.00
48093,zzyzzx,0.0,0.0,14.0,18.0,0.777778,1.00

In [21]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['#posts'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.8700937177970541

In [22]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['#comments'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.7902961016748615

In [23]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['karma'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.8681024797864977

# twitter

In [7]:
import pandas as pd
df=pd.read_csv("../Naman/final_csv/twitter_final.csv")
df

,Unnamed: 0,user_id,user_mentioned,followers_count,friends_count,statuses_count,ratio_friends_count_followers_count,ratio_user_mentioned_statuses_count
0,0,41,0.0,102,76,7517,0.745098,0.000000
1,1,57,5.0,18097,1536,29015,0.084876,0.000172
2,2,224,112.0,57628,898,49056,0.015583,0.002283
3,3,291,30.0,960319,428,39889,0.000446,0.000752
4,4,324,8.0,32007,6436,31070,0.201081,0.000257
...,...,...,...,...,...,...,...,...
1715001,1715001,1334714486176051200,3.0,6,39,10,6.500000,0.300000
1715002,1715002,1334719596956409858,0.0,0,13,4,inf,0.000000
1715003,1715003,1334721974610739203,0.0,3,110,12,36.666667,0.000000
1715004,1715004,1334722394339028992,0.0,0,0,1,1.000000,0.000000
1715005,1715005,1334727465734971392,0.0,0,0,6,1.000000,0.000000

In [8]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['followers_count'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.912507099067313

In [9]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['friends_count'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.7075494599052073

In [10]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['statuses_count'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.7437559055090136

In [11]:
import numpy as np

def gini_coefficient(values):
    # Sort the values
    sorted_values = np.sort(values)
    
    # Calculate the cumulative sum of the sorted values
    cumulative_values = np.cumsum(sorted_values)
    
    # Calculate the Gini coefficient
    n = len(values)
    cumulative_sum = sum((i + 1) * sorted_values[i] for i in range(n))
    total_sum = sum(sorted_values)
    gini_index = (2 * cumulative_sum - (n + 1) * total_sum) / (n * total_sum)
    
    return gini_index

# Calculate the Gini coefficient for the unique_year_month_counts
gini_index = gini_coefficient(df['user_mentioned'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.942923791749206

## Another formula 
 --https://www.statology.org/gini-coefficient-python/
 --https://kimberlyfessel.com/mathematics/applications/gini-use-cases/
 --https://github.com/oliviaguest/gini

In [24]:
import numpy as np

#define function to calculate Gini coefficient
def gini(x):
    total = 0
    for i, xi in enumerate(x[:-1], 1):
        total += np.sum(np.abs(xi - x[i:]))
    return total / (len(x)**2 * np.mean(x))

gini_index = gini_coefficient(df['karma'])

# Display the result
print(f"Gini Coefficient: {gini_index}")

Gini Coefficient: 0.8681024797864977

# 80-20

## Parler

In [27]:
df=pd.read_csv("../Naman/final_csv/parler_final.csv")
df

,Unnamed: 0,creator,user_followers,user_following,#comments,#posts,ratio_following_followers,ratio_comments_posts
0,0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,25.0,195.0,0.302368,0.128205
1,1,a078092e6e2df507bfd12db4713f2db7,33.0,13.0,0.0,0.0,0.393939,1.000000
2,2,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,0.0,0.0,0.328333,1.000000
3,3,a078092e6e2df507bfd12db4710da666,307.0,28.0,0.0,0.0,0.091205,1.000000
4,4,a078092e6e2df507bfd12db471072e00,1600.0,134.0,0.0,0.0,0.083750,1.000000
...,...,...,...,...,...,...,...,...
10789017,12342704,119521e88cf9484a87afa91a9c9c8339,0.0,1.0,0.0,0.0,inf,1.000000
10789018,12342706,dfe689b9e9fc4974865d09f1d7d72597,1.0,12.0,0.0,0.0,12.000000,1.000000
10789019,12342707,6eb75d964f824b02923cab1cc2ffbcdb,0.0,9.0,0.0,0.0,inf,1.000000
10789020,12342708,66f57099e57842d2be2d2ec9ce69657f,0.0,2.0,0.0,0.0,inf,1.000000
10789021,12342710,4cee5a4de9224a13bc34af6cb4f88bfd,0.0,1.0,0.0,0.0,inf,1.000000

In [35]:
df["creator"].is_unique

True

In [34]:
total_sum=df["#posts"].sum()
total_sum

97939980.0

In [29]:
0.8*97939980

78351984.0

In [30]:
df_sorted=df.sort_values(by="#posts",ascending=False)
df_sorted

,Unnamed: 0,creator,user_followers,user_following,#comments,#posts,ratio_following_followers,ratio_comments_posts
2028293,2213468,d917baeb3bef4a0390e22b7a2d870f8c,9200.0,9600.0,12788.0,75341.0,1.043478,0.169735
92740,99738,f380a75fcc024f789582d428e310a218,16000.0,22000.0,5166.0,73474.0,1.375000,0.070311
458361,548151,e11890c2ffc348df9cb703651a3cc9c0,16000.0,9400.0,29428.0,68907.0,0.587500,0.427068
1458084,1606269,9fc7c4e811124aa89eb2d8592335ba45,7200.0,7200.0,2119.0,67502.0,1.000000,0.031392
257929,301412,2225903b6a664e559c8c6b293cb2cb57,22000.0,11000.0,3277.0,66384.0,0.500000,0.049364
...,...,...,...,...,...,...,...,...
4425542,4894833,258ec12751574754bbd4a4bc70aa214c,2.0,17.0,0.0,0.0,8.500000,1.000000
4425541,4894831,ee5147e6d1e3486fb156083a6fd926b2,2.0,15.0,0.0,0.0,7.500000,1.000000
4425540,4894830,c47f60c32fa04e5ba56d109fcb8894f2,18.0,17.0,0.0,0.0,0.944444,1.000000
4425539,4894829,32416425df1440b580bed6b2ca700eb1,5.0,29.0,0.0,0.0,5.800000,1.000000
10789021,12342710,4cee5a4de9224a13bc34af6cb4f88bfd,0.0,1.0,0.0,0.0,inf,1.000000

In [31]:
df_sorted['cumulative_sum'] = df_sorted['#posts'].cumsum()

In [32]:
df_sorted

,Unnamed: 0,creator,user_followers,user_following,#comments,#posts,ratio_following_followers,ratio_comments_posts,cumulative_sum
2028293,2213468,d917baeb3bef4a0390e22b7a2d870f8c,9200.0,9600.0,12788.0,75341.0,1.043478,0.169735,75341.0
92740,99738,f380a75fcc024f789582d428e310a218,16000.0,22000.0,5166.0,73474.0,1.375000,0.070311,148815.0
458361,548151,e11890c2ffc348df9cb703651a3cc9c0,16000.0,9400.0,29428.0,68907.0,0.587500,0.427068,217722.0
1458084,1606269,9fc7c4e811124aa89eb2d8592335ba45,7200.0,7200.0,2119.0,67502.0,1.000000,0.031392,285224.0
257929,301412,2225903b6a664e559c8c6b293cb2cb57,22000.0,11000.0,3277.0,66384.0,0.500000,0.049364,351608.0
...,...,...,...,...,...,...,...,...,...
4425542,4894833,258ec12751574754bbd4a4bc70aa214c,2.0,17.0,0.0,0.0,8.500000,1.000000,97939980.0
4425541,4894831,ee5147e6d1e3486fb156083a6fd926b2,2.0,15.0,0.0,0.0,7.500000,1.000000,97939980.0
4425540,4894830,c47f60c32fa04e5ba56d109fcb8894f2,18.0,17.0,0.0,0.0,0.944444,1.000000,97939980.0
4425539,4894829,32416425df1440b580bed6b2ca700eb1,5.0,29.0,0.0,0.0,5.800000,1.000000,97939980.0
10789021,12342710,4cee5a4de9224a13bc34af6cb4f88bfd,0.0,1.0,0.0,0.0,inf,1.000000,97939980.0

In [36]:
people=10789022*0.2

In [42]:
o=int(people)
o

2157804

In [44]:
df_sorted.iloc[:o]["cumulative_sum"].max()

97667086.0

In [49]:
df_sorted = df.sort_values(by='#posts', ascending=False)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['#posts'].cumsum()

# Calculate the total sum
total_sum = df_sorted['#posts'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: True
80% value: 78351984.0
20% value: 97667086.0

In [50]:
df_sorted = df.sort_values(by='#posts', ascending=True)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['#posts'].cumsum()

# Calculate the total sum
total_sum = df_sorted['#posts'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: False
80% value: 78351984.0
20% value: 0.0

In [51]:
df_sorted = df.sort_values(by='#comments', ascending=False)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['#comments'].cumsum()

# Calculate the total sum
total_sum = df_sorted['#comments'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: True
80% value: 35168676.800000004
20% value: 43960846.0

## dotwin

In [52]:
df=pd.read_csv("../Naman/final_csv/dotwin_final.csv")
df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,--1--,1.0,1.0,37.0,231.0,0.160173,1.00
1,-2b-,221.0,5.0,58.0,258.0,0.224806,44.20
2,-Lin-Wood,7.0,1.0,6.0,13.0,0.461538,7.00
3,-ProudPatriot-,1.0,4.0,1.0,23.0,0.043478,0.25
4,-REEEEEEEDACTED-,1.0,2.0,103.0,1029.0,0.100097,0.50
...,...,...,...,...,...,...,...
48089,zyklonbravo,0.0,0.0,66.0,73.0,0.904110,1.00
48090,zz556,0.0,0.0,7.0,11.0,0.636364,1.00
48091,zzRrocks,0.0,0.0,13.0,27.0,0.481481,1.00
48092,zzyzxx,0.0,0.0,2.0,2.0,1.000000,1.00
48093,zzyzzx,0.0,0.0,14.0,18.0,0.777778,1.00

In [53]:
df_sorted = df.sort_values(by='#posts', ascending=False)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['#posts'].cumsum()

# Calculate the total sum
total_sum = df_sorted['#posts'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: True
80% value: 181742.40000000002
20% value: 205357.0

In [54]:
df_sorted = df.sort_values(by='#comments', ascending=False)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['#comments'].cumsum()

# Calculate the total sum
total_sum = df_sorted['#comments'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: True
80% value: 1281320.8
20% value: 1337629.0

In [33]:
df_sorted = df.sort_values(by='#comments', ascending=True)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['#comments'].cumsum()

# Calculate the total sum
total_sum = df_sorted['#comments'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: False
80% value: 35168676.800000004
20% value: 0.0

In [56]:
df_sorted = df.sort_values(by='karma', ascending=False)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['karma'].cumsum()

# Calculate the total sum
total_sum = df_sorted['karma'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: True
80% value: 7763207.2
20% value: 8742454.0

In [57]:
df_sorted = df.sort_values(by='karma', ascending=True)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['karma'].cumsum()

# Calculate the total sum
total_sum = df_sorted['karma'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: False
80% value: 7763207.2
20% value: -12942.0

## twitter

In [27]:
df=pd.read_csv("../Naman/final_csv/user_data_twitter.csv")
df

,id,tweet_id,user_id,user_screen_name,user_name,tweet_time,location,description,protected,verified,user_created_at,followers_count,friends_count,statuses_count,favorites_count,rn
0,200594014,1330263124721737729,41,drx,drx,2020-11-21 21:33:38,Deep in the Archives,Adept bubble burster. Good problem connoisseur...,False,False,2006-03-23 00:05:49,102,76,7517,9988,1
1,186732678,1331107649123971074,57,SarahM,Sarah Milstein,2020-11-24 05:29:28,Bklyn 75%; SF 25%,Leaderizing and manageering for @Mailchimp eng...,False,True,2006-04-01 02:05:23,18097,1536,29015,46245,1
2,152714043,1334230798036164609,224,davepell,Dave Pell,2020-12-02 20:19:45,San Francisco,"Managing Editor, Internet.",False,True,2006-05-01 22:17:42,57628,898,49056,14851,1
3,156812061,1334574567969308674,291,goldman,Jason Goldman,2020-12-03 19:05:46,Various,I like the work about the work. Places practic...,False,True,2006-05-20 19:46:03,960319,428,39889,32984,1
4,152104129,1334179632166416387,324,chrisfralic,Chris Fralic,2020-12-02 16:56:26,#BadThingsHappenInPhiladelphia,Board Partner @FirstRound. Technology historia...,False,True,2006-06-06 15:04:24,32007,6436,31070,32276,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1715001,158561819,1334721351257612289,1334714486176051200,LarraySoThicc,Maddie,2020-12-04 04:49:02,NaN,I love @larrayxo ❤️ This is a Larray fan page❤...,False,False,2020-12-04 04:21:58,6,39,10,6,1
1715002,158697103,1334732697512660992,1334719596956409858,LydiaFe71731620,Lydia Fernandes,2020-12-04 05:34:07,NaN,NaN,False,False,2020-12-04 04:42:23,0,13,4,7,1
1715003,158744538,1334736677856661507,1334721974610739203,JesusCh32131944,Jesus Christ,2020-12-04 05:49:56,NaN,NaN,False,False,2020-12-04 04:51:42,3,110,12,51,1
1715004,158599052,1334724472553795586,1334722394339028992,Edward18990382,Edward,2020-12-04 05:01:26,NaN,NaN,False,False,2020-12-04 04:54:26,0,0,1,0,1
1715005,158760754,1334738037188808704,1334727465734971392,PjTrump2020,PjTrump2020,2020-12-04 05:55:20,NaN,Light eliminates darkness,False,False,2020-12-04 05:13:54,0,0,6,14,1

In [14]:
df_sorted = df.sort_values(by='statuses_count', ascending=True)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['statuses_count'].cumsum()

# Calculate the total sum
total_sum = df_sorted['statuses_count'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: False
80% value: 28574273532.0
20% value: 103306210.0

In [15]:
df_sorted = df.sort_values(by='statuses_count', ascending=False)

# Calculate the cumulative sum
df_sorted['cumulative_sum'] = df_sorted['statuses_count'].cumsum()

# Calculate the total sum
total_sum = df_sorted['statuses_count'].sum()

# Calculate the 80% value of the total sum
eighty_percent_value = 0.8 * total_sum

# Determine the cutoff for 20% of the items
cutoff_index = int(len(df_sorted) * 0.2)
cutoff_index = max(cutoff_index, 1)  # Ensure at least one item is included

# Calculate the cumulative sum for the top 20% of items
top_20_percent_value = df_sorted.iloc[cutoff_index-1]['cumulative_sum']

# Check if 80% of the total sum is within the top 20% of the items
is_80_percent_covered = top_20_percent_value >= eighty_percent_value

# Display the result
print(f"80% of the work is done by 20% of the people: {is_80_percent_covered}")
print(f"80% value: {eighty_percent_value}")
print(f"20% value: {top_20_percent_value}")

80% of the work is done by 20% of the people: False
80% value: 28574273532.0
20% value: 27681574838.0

# Hoover Index

- https://www.un.org/en/development/desa/policy/wess/wess_dev_issues/dsp_policy_02.pdf

## Twitter

In [17]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["followers_count"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.7665

In [18]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["friends_count"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.5453

In [19]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["statuses_count"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.5794

In [20]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["user_mentioned"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.8033

## Dotwin

In [21]:
df=pd.read_csv("../Naman/final_csv/dotwin_final.csv")
df

,author,comments_received,#posts,#comments,karma,ratio_#comments_karma,ratio_comments_received_#posts
0,--1--,1.0,1.0,37.0,231.0,0.160173,1.00
1,-2b-,221.0,5.0,58.0,258.0,0.224806,44.20
2,-Lin-Wood,7.0,1.0,6.0,13.0,0.461538,7.00
3,-ProudPatriot-,1.0,4.0,1.0,23.0,0.043478,0.25
4,-REEEEEEEDACTED-,1.0,2.0,103.0,1029.0,0.100097,0.50
...,...,...,...,...,...,...,...
48089,zyklonbravo,0.0,0.0,66.0,73.0,0.904110,1.00
48090,zz556,0.0,0.0,7.0,11.0,0.636364,1.00
48091,zzRrocks,0.0,0.0,13.0,27.0,0.481481,1.00
48092,zzyzxx,0.0,0.0,2.0,2.0,1.000000,1.00
48093,zzyzzx,0.0,0.0,14.0,18.0,0.777778,1.00

In [22]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["#posts"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.7104

In [23]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["#comments"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.6354

In [24]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["karma"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.7069

In [25]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["comments_received"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.7904

## Parler

In [28]:
df=pd.read_csv("../Naman/final_csv/parler_final.csv")
df

,Unnamed: 0,creator,user_followers,user_following,#comments,#posts,ratio_following_followers,ratio_comments_posts
0,0,a078092e6e2df507bfd12db4710709ec,549.0,166.0,25.0,195.0,0.302368,0.128205
1,1,a078092e6e2df507bfd12db4713f2db7,33.0,13.0,0.0,0.0,0.393939,1.000000
2,2,a078092e6e2df507bfd12db471063dd0,1200.0,394.0,0.0,0.0,0.328333,1.000000
3,3,a078092e6e2df507bfd12db4710da666,307.0,28.0,0.0,0.0,0.091205,1.000000
4,4,a078092e6e2df507bfd12db471072e00,1600.0,134.0,0.0,0.0,0.083750,1.000000
...,...,...,...,...,...,...,...,...
10789017,12342704,119521e88cf9484a87afa91a9c9c8339,0.0,1.0,0.0,0.0,inf,1.000000
10789018,12342706,dfe689b9e9fc4974865d09f1d7d72597,1.0,12.0,0.0,0.0,12.000000,1.000000
10789019,12342707,6eb75d964f824b02923cab1cc2ffbcdb,0.0,9.0,0.0,0.0,inf,1.000000
10789020,12342708,66f57099e57842d2be2d2ec9ce69657f,0.0,2.0,0.0,0.0,inf,1.000000
10789021,12342710,4cee5a4de9224a13bc34af6cb4f88bfd,0.0,1.0,0.0,0.0,inf,1.000000

In [29]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["user_followers"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.8656

In [30]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["user_following"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.6685

In [31]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["#comments"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.9382

In [32]:
import numpy as np

def hoover_index(incomes):
    """
    Calculate the Hoover index of an income distribution.
    """
    incomes = np.array(incomes)
    mean_income = np.mean(incomes)
    hoover = 0.5 * np.sum(np.abs(incomes - mean_income)) / np.sum(incomes)
    return hoover

# Example data


# Calculate Hoover index
hoover = hoover_index(df["#posts"])
print(f'Hoover index: {hoover:.4f}')

Hoover index: 0.9257